Expose the UnicodeDecodeError error
Starting app gwenn-test in org dgodd / space dgodd as admin...
Creating container
Successfully created container
Downloading app package...
Downloaded app package (740B)
Staging...
Downloaded buildpack `https://github.com/cloudfoundry/php-buildpack/releases/download/v4.3.38/php-buildpack-v4.3.38.zip` (282.5K)-------> Buildpack version 4.3.38
Installing HTTPD
HTTPD 2.4.27
Downloaded [https://buildpacks.cloudfoundry.org/dependencies/httpd/httpd-2.4.27-linux-x64-ebe06494.tgz] to [/tmp]
Warning: PHP_EXTENSIONS in options.json is deprecated. See: http://docs.cloudfoundry.org/buildpacks/php/gsg-php-config.html
Installing PHP
PHP 5.6.31
Downloaded [https://buildpacks.cloudfoundry.org/dependencies/php/php-5.6.31-linux-x64-c495c457.tgz] to [/tmp]
Downloaded [https://buildpacks.cloudfoundry.org/dependencies/php/php-5.6.31-linux-x64-c495c457.tgz] to [/tmp]
Downloaded [https://buildpacks.cloudfoundry.org/dependencies/composer/composer-1.4.2-3a1d1c6c.phar] to [/tmp]
PROTIP: Include a `composer.lock` file with your application! This will make sure the exact same version of dependencies are used when you deploy to CloudFoundry.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   373  100   373    0     0   2018      0 --:--:-- --:--:-- --:--:--  2038
-----> Composer command failed
Traceback (most recent call last):
  File "/tmp/buildpacks/9b5a6f480fd8c77c8b37a6162f17ea3b/scripts/compile.py", line 55, in <module>
    .from_build_pack('lib/additional_commands')
  File "/tmp/buildpacks/9b5a6f480fd8c77c8b37a6162f17ea3b/lib/build_pack_utils/builder.py", line 209, in extensions
    process_extension(path, ctx, 'compile', process, args=[self])
  File "/tmp/buildpacks/9b5a6f480fd8c77c8b37a6162f17ea3b/lib/build_pack_utils/utils.py", line 69, in process_extension
    success(getattr(extn, to_call)(*args))
  File "/tmp/buildpacks/9b5a6f480fd8c77c8b37a6162f17ea3b/extensions/composer/extension.py", line 429, in compile
    return composer.compile(install)
  File "/tmp/buildpacks/9b5a6f480fd8c77c8b37a6162f17ea3b/lib/extension_helpers.py", line 154, in compile
    self._compile(install)
  File "/tmp/buildpacks/9b5a6f480fd8c77c8b37a6162f17ea3b/extensions/composer/extension.py", line 196, in _compile
    self.run()
  File "/tmp/buildpacks/9b5a6f480fd8c77c8b37a6162f17ea3b/extensions/composer/extension.py", line 331, in run
    *self._ctx['COMPOSER_INSTALL_OPTIONS'])
  File "/tmp/buildpacks/9b5a6f480fd8c77c8b37a6162f17ea3b/extensions/composer/extension.py", line 373, in run
    env=self._build_composer_environment(),
  File "/tmp/buildpacks/9b5a6f480fd8c77c8b37a6162f17ea3b/extensions/composer/extension.py", line 363, in _build_composer_environment
    for (key, val) in env.iteritems()]))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 31: ordinal not in range(128)
Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223
Destroying container
Successfully destroyed container

FAILED
Error restarting application: BuildpackCompileFailed